### ISSUE TITLE
Failed to open native connection to Cassandra at {127.0.0.1}:9042

### ISSUE THREAD

**Issue by anandaksh** [Ramasubramanian/analytics_demo#1]
hitting below while doing "mvn clean install":

2017-06-13 21:35:09.174  INFO 7488 --- [           main] .s.b.c.e.j.JettyEmbeddedServletContainer : Jetty started on port(s) 9000
2017-06-13 21:35:09.182  INFO 7488 --- [           main] o.a.maven.surefire.booter.ForkedBooter   : Started ForkedBooter in 13.29 seconds (JVM running for 14.81)
Exception in thread "Thread-38" java.io.IOException: Failed to open native connection to Cassandra at {127.0.0.1}:9042
	at com.datastax.spark.connector.cql.CassandraConnector$.com$datastax$spark$connector$cql$CassandraConnector$$createSession(CassandraConnector.scala:173)
	at com.datastax.spark.connector.cql.CassandraConnector$$anonfun$2.apply(CassandraConnector.scala:159)
	at com.datastax.spark.connector.cql.CassandraConnector$$anonfun$2.apply(CassandraConnector.scala:159)
	at com.datastax.spark.connector.cql.RefCountedCache.createNewValueAndKeys(RefCountedCache.scala:31)
	at com.datastax.spark.connector.cql.RefCountedCache.acquire(RefCountedCache.scala:56)
	at com.datastax.spark.connector.cql.CassandraConnector.openSession(CassandraConnector.scala:70)
	at com.datastax.spark.connector.cql.CassandraConnector.withSessionDo(CassandraConnector.scala:96)
	at com.datastax.spark.connector.cql.CassandraConnector.withClusterDo(CassandraConnector.scala:107)
	at com.datastax.spark.connector.cql.Schema$.fromCassandra(Schema.scala:134)
	at com.datastax.spark.connector.writer.TableWriter$.apply(TableWriter.scala:158)
	at com.datastax.spark.connector.streaming.DStreamFunctions.saveToCassandra(DStreamFunctions.scala:25)
	at com.datastax.spark.connector.japi.DStreamJavaFunctions.saveToCassandra(DStreamJavaFunctions.java:41)
	at com.datastax.spark.connector.japi.RDDAndDStreamCommonJavaFunctions$WriterBuilder.saveToCassandra(RDDAndDStreamCommonJavaFunctions.java:394)
	at in.raam.analytics.app.AnalyticsApplication.lambda$0(AnalyticsApplication.java:57)
	at in.raam.analytics.util.InMemorySparkStreamDataInputPipe$1.run(InMemorySparkStreamDataInputPipe.java:27)
Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /127.0.0.1:9042 (com.datastax.driver.core.exceptions.InvalidQueryException: unconfigured table schema_keyspaces))
	at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:220)
	at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:78)
	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1231)
	at com.datastax.driver.core.Cluster.getMetadata(Cluster.java:334)
	at com.datastax.spark.connector.cql.CassandraConnector$.com$datastax$spark$connector$cql$CassandraConnector$$createSession(CassandraConnector.scala:166)
	... 14 more
2017-06-13 21:35:15.167  WARN 7488 --- [ qtp91220956-19] o.eclipse.jetty.servlet.ServletHandler   : 

org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.reflect.UndeclaredThrowableException
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:978)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:857)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:842)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1496)
	at org.springframework.boot.actuate.autoconfigure.EndpointWebMvcAutoConfiguration$ApplicationContextHeaderFilter.doFilterInternal(EndpointWebMvcAutoConfiguration.java:291)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1467)
	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:102)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1467)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1467)
	at org.springframework.boot.actuate.autoconfigure.MetricFilterAutoConfiguration$MetricsFilter.doFilterInternal(MetricFilterAutoConfiguration.java:90)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1467)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:370)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:971)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1033)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.UndeclaredThrowableException: null
	at in.raam.analytics.dao.SparkPageViewDAO$$EnhancerBySpringCGLIB$$ecf2f2a4.fetchPageViewsByUser(<generated>)
	at in.raam.analytics.app.controller.AnalyticsController.getPageViewsPerUser(AnalyticsController.java:102)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:777)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:706)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:943)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:877)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:966)
	... 40 common frames omitted
Caused by: java.io.IOException: Failed to open native connection to Cassandra at {127.0.0.1}:9042
	at com.datastax.spark.connector.cql.CassandraConnector$.com$datastax$spark$connector$cql$CassandraConnector$$createSession(CassandraConnector.scala:173)
	at com.datastax.spark.connector.cql.CassandraConnector$$anonfun$2.apply(CassandraConnector.scala:159)
	at com.datastax.spark.connector.cql.CassandraConnector$$anonfun$2.apply(CassandraConnector.scala:159)
	at com.datastax.spark.connector.cql.RefCountedCache.createNewValueAndKeys(RefCountedCache.scala:31)
	at com.datastax.spark.connector.cql.RefCountedCache.acquire(RefCountedCache.scala:56)
	at com.datastax.spark.connector.cql.CassandraConnector.openSession(CassandraConnector.scala:70)
	at com.datastax.spark.connector.cql.CassandraConnector.withSessionDo(CassandraConnector.scala:96)
	at com.datastax.spark.connector.cql.CassandraConnector.withClusterDo(CassandraConnector.scala:107)
	at com.datastax.spark.connector.cql.Schema$.fromCassandra(Schema.scala:134)
	at com.datastax.spark.connector.rdd.CassandraRDD.tableDef$lzycompute(CassandraRDD.scala:246)
	at com.datastax.spark.connector.rdd.CassandraRDD.tableDef(CassandraRDD.scala:245)
	at com.datastax.spark.connector.rdd.CassandraRDD.verify$lzycompute(CassandraRDD.scala:304)
	at com.datastax.spark.connector.rdd.CassandraRDD.verify(CassandraRDD.scala:301)
	at com.datastax.spark.connector.rdd.CassandraRDD.getPartitions(CassandraRDD.scala:330)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:222)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:220)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:220)
	at org.apache.spark.rdd.MappedRDD.getPartitions(MappedRDD.scala:28)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:222)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:220)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:220)
	at org.apache.spark.rdd.RDD.take(RDD.scala:1077)
	at org.apache.spark.api.java.JavaRDDLike$class.take(JavaRDDLike.scala:421)
	at org.apache.spark.api.java.JavaRDD.take(JavaRDD.scala:32)
	at in.raam.analytics.dao.SparkPageViewDAO.fetchPageViewsByUser(SparkPageViewDAO.java:40)
	at in.raam.analytics.dao.SparkPageViewDAO$$FastClassBySpringCGLIB$$679b37cf.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:717)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653)
	... 55 common frames omitted
Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /127.0.0.1:9042 (com.datastax.driver.core.exceptions.InvalidQueryException: unconfigured table schema_keyspaces))
	at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:220)
	at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:78)
	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1231)
	at com.datastax.driver.core.Cluster.getMetadata(Cluster.java:334)
	at com.datastax.spark.connector.cql.CassandraConnector$.com$datastax$spark$connector$cql$CassandraConnector$$createSession(CassandraConnector.scala:166)
	... 88 common frames omitted

2017-06-13 21:35:15.179  WARN 7488 --- [ qtp91220956-19] o.eclipse.jetty.servlet.ServletHandler   : /analytics/1497369914919%40domain.com/pageviews

java.lang.reflect.UndeclaredThrowableException: null
	at in.raam.analytics.dao.SparkPageViewDAO$$EnhancerBySpringCGLIB$$ecf2f2a4.fetchPageViewsByUser(<generated>)
	at in.raam.analytics.app.controller.AnalyticsController.getPageViewsPerUser(AnalyticsController.java:102)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:777)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:706)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:943)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:877)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:966)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:857)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:842)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1496)
	at org.springframework.boot.actuate.autoconfigure.EndpointWebMvcAutoConfiguration$ApplicationContextHeaderFilter.doFilterInternal(EndpointWebMvcAutoConfiguration.java:291)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1467)
	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:102)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1467)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1467)
	at org.springframework.boot.actuate.autoconfigure.MetricFilterAutoConfiguration$MetricsFilter.doFilterInternal(MetricFilterAutoConfiguration.java:90)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1467)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:370)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:971)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1033)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Failed to open native connection to Cassandra at {127.0.0.1}:9042
	at com.datastax.spark.connector.cql.CassandraConnector$.com$datastax$spark$connector$cql$CassandraConnector$$createSession(CassandraConnector.scala:173)
	at com.datastax.spark.connector.cql.CassandraConnector$$anonfun$2.apply(CassandraConnector.scala:159)
	at com.datastax.spark.connector.cql.CassandraConnector$$anonfun$2.apply(CassandraConnector.scala:159)
	at com.datastax.spark.connector.cql.RefCountedCache.createNewValueAndKeys(RefCountedCache.scala:31)
	at com.datastax.spark.connector.cql.RefCountedCache.acquire(RefCountedCache.scala:56)
	at com.datastax.spark.connector.cql.CassandraConnector.openSession(CassandraConnector.scala:70)
	at com.datastax.spark.connector.cql.CassandraConnector.withSessionDo(CassandraConnector.scala:96)
	at com.datastax.spark.connector.cql.CassandraConnector.withClusterDo(CassandraConnector.scala:107)
	at com.datastax.spark.connector.cql.Schema$.fromCassandra(Schema.scala:134)
	at com.datastax.spark.connector.rdd.CassandraRDD.tableDef$lzycompute(CassandraRDD.scala:246)
	at com.datastax.spark.connector.rdd.CassandraRDD.tableDef(CassandraRDD.scala:245)
	at com.datastax.spark.connector.rdd.CassandraRDD.verify$lzycompute(CassandraRDD.scala:304)
	at com.datastax.spark.connector.rdd.CassandraRDD.verify(CassandraRDD.scala:301)
	at com.datastax.spark.connector.rdd.CassandraRDD.getPartitions(CassandraRDD.scala:330)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:222)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:220)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:220)
	at org.apache.spark.rdd.MappedRDD.getPartitions(MappedRDD.scala:28)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:222)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:220)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:220)
	at org.apache.spark.rdd.RDD.take(RDD.scala:1077)
	at org.apache.spark.api.java.JavaRDDLike$class.take(JavaRDDLike.scala:421)
	at org.apache.spark.api.java.JavaRDD.take(JavaRDD.scala:32)
	at in.raam.analytics.dao.SparkPageViewDAO.fetchPageViewsByUser(SparkPageViewDAO.java:40)
	at in.raam.analytics.dao.SparkPageViewDAO$$FastClassBySpringCGLIB$$679b37cf.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:717)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653)
	... 55 common frames omitted
Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /127.0.0.1:9042 (com.datastax.driver.core.exceptions.InvalidQueryException: unconfigured table schema_keyspaces))
	at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:220)
	at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:78)
	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1231)
	at com.datastax.driver.core.Cluster.getMetadata(Cluster.java:334)
	at com.datastax.spark.connector.cql.CassandraConnector$.com$datastax$spark$connector$cql$CassandraConnector$$createSession(CassandraConnector.scala:166)
	... 88 common frames omitted

Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 20.1 sec - in in.raam.analytics.app.controllers.AnalyticsControllerTest
2017-06-13 21:35:15.296  INFO 7488 --- [       Thread-1] ationConfigEmbeddedWebApplicationContext : Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@222545dc: startup date [Tue Jun 13 21:34:56 IST 2017]; root of context hierarchy
2017-06-13 21:35:15.327  INFO 7488 --- [       Thread-1] o.e.jetty.server.handler.ContextHandler  : stopped o.e.j.s.ServletContextHandler{/streaming/json,null}
2017-06-13 21:35:15.327  INFO 7488 --- [       Thread-1] o.e.jetty.server.handler.ContextHandler  : stopped o.e.j.s.ServletContextHandler{/streaming,null}
2017-06-13 21:35:15.328  INFO 7488 --- [       Thread-1] o.e.jetty.server.handler.ContextHandler  : stopped o.e.j.s.ServletContextHandler{/metrics/json,null}
2017-06-13 21:35:15.328  INFO 7488 --- [       Thread-1] o.e.jetty.server.handler.ContextHandler  : stopped o.e.j.s.ServletContextHandler{/stages/stage/kill,null}
2017-06-13 21:35:15.329  INFO 7488 --- [       Thread-1] o.e.jetty.server.handler.ContextHandler  : stopped o.e.j.s.ServletContextHandler{/,null}
2017-06-13 21:35:15.330  INFO 7488 --- [       Thread-1] o.e.jetty.server.handler.ContextHandler  : stopped o.e.j.s.ServletContextHandler{/static,null}
2017-06-13 21:35:15.331  INFO 7488 --- [       Thread-1] o.e.jetty.server.handler.ContextHandler  : stopped o.e.j.s.ServletContextHandler{/executors/threadDump/json,null}
2017-06-13 21:35:15.331  INFO 7488 --- [       Thread-1] o.e.jetty.server.handler.ContextHandler  : stopped o.e.j.s.ServletContextHandler{/executors/threadDump,null}
2017-06-13 21:35:15.332  INFO 7488 --- [       Thread-1] o.e.jetty.server.handler.ContextHandler  : stopped o.e.j.s.ServletContextHandler{/executors/json,null}
2017-06-13 21:35:15.332  INFO 7488 --- [       Thread-1] o.e.jetty.server.handler.ContextHandler  : stopped o.e.j.s.ServletContextHandler{/executors,null}
2017-06-13 21:35:15.333  INFO 7488 --- [       Thread-1] o.e.jetty.server.handler.ContextHandler  : stopped o.e.j.s.ServletContextHandler{/environment/json,null}
2017-06-13 21:35:15.333  INFO 7488 --- [       Thread-1] o.e.jetty.server.handler.ContextHandler  : stopped o.e.j.s.ServletContextHandler{/environment,null}
2017-06-13 21:35:15.333  INFO 7488 --- [       Thread-1] o.e.jetty.server.handler.ContextHandler  : stopped o.e.j.s.ServletContextHandler{/storage/rdd/json,null}
2017-06-13 21:35:15.334  INFO 7488 --- [       Thread-1] o.e.jetty.server.handler.ContextHandler  : stopped o.e.j.s.ServletContextHandler{/storage/rdd,null}
2017-06-13 21:35:15.334  INFO 7488 --- [       Thread-1] o.e.jetty.server.handler.ContextHandler  : stopped o.e.j.s.ServletContextHandler{/storage/json,null}
2017-06-13 21:35:15.335  INFO 7488 --- [       Thread-1] o.e.jetty.server.handler.ContextHandler  : stopped o.e.j.s.ServletContextHandler{/storage,null}
2017-06-13 21:35:15.335  INFO 7488 --- [       Thread-1] o.e.jetty.server.handler.ContextHandler  : stopped o.e.j.s.ServletContextHandler{/stages/pool/json,null}
2017-06-13 21:35:15.336  INFO 7488 --- [       Thread-1] o.e.jetty.server.handler.ContextHandler  : stopped o.e.j.s.ServletContextHandler{/stages/pool,null}
2017-06-13 21:35:15.336  INFO 7488 --- [       Thread-1] o.e.jetty.server.handler.ContextHandler  : stopped o.e.j.s.ServletContextHandler{/stages/stage/json,null}
2017-06-13 21:35:15.337  INFO 7488 --- [       Thread-1] o.e.jetty.server.handler.ContextHandler  : stopped o.e.j.s.ServletContextHandler{/stages/stage,null}
2017-06-13 21:35:15.337  INFO 7488 --- [       Thread-1] o.e.jetty.server.handler.ContextHandler  : stopped o.e.j.s.ServletContextHandler{/stages/json,null}
2017-06-13 21:35:15.337  INFO 7488 --- [       Thread-1] o.e.jetty.server.handler.ContextHandler  : stopped o.e.j.s.ServletContextHandler{/stages,null}
2017-06-13 21:35:15.338  INFO 7488 --- [       Thread-1] o.e.jetty.server.handler.ContextHandler  : stopped o.e.j.s.ServletContextHandler{/jobs/job/json,null}
2017-06-13 21:35:15.338  INFO 7488 --- [       Thread-1] o.e.jetty.server.handler.ContextHandler  : stopped o.e.j.s.ServletContextHandler{/jobs/job,null}
2017-06-13 21:35:15.338  INFO 7488 --- [       Thread-1] o.e.jetty.server.handler.ContextHandler  : stopped o.e.j.s.ServletContextHandler{/jobs/json,null}
2017-06-13 21:35:15.338  INFO 7488 --- [       Thread-1] o.e.jetty.server.handler.ContextHandler  : stopped o.e.j.s.ServletContextHandler{/jobs,null}
2017-06-13 21:35:15.394  INFO 7488 --- [       Thread-1] org.apache.spark.scheduler.DAGScheduler  : Stopping DAGScheduler
2017-06-13 21:35:16.451  INFO 7488 --- [t-dispatcher-16] o.a.spark.MapOutputTrackerMasterActor    : MapOutputTrackerActor stopped!
2017-06-13 21:35:16.456  INFO 7488 --- [       Thread-1] org.apache.spark.storage.MemoryStore     : MemoryStore cleared
2017-06-13 21:35:16.459  INFO 7488 --- [       Thread-1] org.apache.spark.storage.BlockManager    : BlockManager stopped
2017-06-13 21:35:16.461  INFO 7488 --- [       Thread-1] o.a.spark.storage.BlockManagerMaster     : BlockManagerMaster stopped
2017-06-13 21:35:16.463  INFO 7488 --- [       Thread-1] org.apache.spark.SparkContext            : Successfully stopped SparkContext
2017-06-13 21:35:16.471  INFO 7488 --- [t-dispatcher-16] emoteActorRefProvider$RemotingTerminator : Shutting down remote daemon.
2017-06-13 21:35:16.474  INFO 7488 --- [t-dispatcher-16] emoteActorRefProvider$RemotingTerminator : Remote daemon shut down; proceeding with flushing remote transports.
2017-06-13 21:35:16.480  INFO 7488 --- [       Thread-1] /                                        : Destroying Spring FrameworkServlet 'dispatcherServlet'
2017-06-13 21:35:16.481  INFO 7488 --- [       Thread-1] o.e.jetty.server.handler.ContextHandler  : stopped o.s.b.c.e.j.JettyEmbeddedWebAppContext{/,null}
2017-06-13 21:35:16.511  INFO 7488 --- [t-dispatcher-16] emoteActorRefProvider$RemotingTerminator : Remoting shut down.

Results :

Tests run: 3, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 33.373 s
[INFO] Finished at: 2017-06-13T21:35:16+05:30
[INFO] Final Memory: 17M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test (default-test) on project analytics_demo: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test failed: There was an error in the forked process
[ERROR] java.lang.AbstractMethodError: org.apache.maven.surefire.report.PojoStackTraceWriter.smartTrimmedStackTrace()Ljava/lang/String;
[ERROR] at org.apache.maven.surefire.booter.ForkingRunListener.encode(ForkingRunListener.java:328)
[ERROR] at org.apache.maven.surefire.booter.ForkingRunListener.encode(ForkingRunListener.java:312)
[ERROR] at org.apache.maven.surefire.booter.ForkingRunListener.toString(ForkingRunListener.java:258)
[ERROR] at org.apache.maven.surefire.booter.ForkingRunListener.testError(ForkingRunListener.java:132)
[ERROR] at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:162)
[ERROR] at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:

**Comment by Ramasubramanian** [comment]
Error message means Spark is not able to connect to Cassandra instance. Could be couple of reasons:
`Caused by: java.io.IOException: Failed to open native connection to Cassandra at {127.0.0.1}:9042
at `

1. Cassandra is not up or not running on the specified port
2. The driver you are using for Cassandra and the cassandra version might be having a mismatch. Since this demo is a bit old try upgrading the driver version in pom.xml
